### ISSUE TITLE
Compare algorithms

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/introduction-to-algorithms#1]
I would suggest you to compare the algorithms to prove which one is more effective. 

Workout a setup in which you can use the three different approaches (algorithms) with the same initial array. The array should be very big in order to see real differences. 

Print something like: 

Algorithm 1 => XX seconds
Algorithm 2 => XX seconds
.....

NOTE: be critical with all the things you learn. Ask yourself why one algorithm is better than the rest. Running the examples from the book it is simple. Understanding and proving that one is better is something else.

**Comment by rafaelklaessen** [comment]
Hm, I learned that the efficiency of an algorithm is determined with the order of growth (like Θ(n lg n)). This is calculated in a regular math way.

**Comment by rafaelklaessen** [comment]
So I don't put it on GitHub. (And besides that, I still don't understand it completely so I'm practicing it, but not via a computer)

**Comment by Titogelo** [comment]
That's one step ahead ;-). 

That's good, leave it for now then. But, I wanted you to not overlook this part about the complexity of an algorithm (it is very very very important) :-)

Well done! You are on the good track.
